Comments
noseplug/monorepo pull request #32
Opened 2017-02-10 19:55 UTC by Bombergames

adds comments object and shows them in a listview in odorevent details

2017-02-10 20:17 UTC, estebanlau requested changes

2017-02-10 20:17 UTC, estebanlau commented on android/app/src/main/java/edu/gatech/cs/environmentalodors/MapsActivity.java
> +            Comment tempComment = new Comment();
No line breaks before the opening braces. Change everywhere else as well.

2017-02-10 20:17 UTC, estebanlau commented on android/app/src/main/java/edu/gatech/cs/environmentalodors/models/Comment.java
> +        this.author = author;
No line breaks before opening braces.

2017-02-10 20:17 UTC, estebanlau commented on android/app/src/main/java/edu/gatech/cs/environmentalodors/models/OdorEvent.java
> +    public List<Comment> getComments() { return comments; }
We should have consistent formatting. Insert a line break after opening braces.

2017-02-10 20:17 UTC, estebanlau commented on android/app/src/main/java/edu/gatech/cs/environmentalodors/MapsActivity.java
> +        int commentCount = 5;
Better practice to declare variables as close as possible to their location of use.

2017-02-15 22:57 UTC, Bombergames commented on android/app/src/main/java/edu/gatech/cs/environmentalodors/MapsActivity.java
> +        int commentCount = 5;
I think it'll be fine this way - it allows easy editing of the test without having to sift through the code.  That is probably a good policy for non-tests though.

2017-02-15 23:37 UTC, Bombergames commented
New commit adds a way to make comments throught ui, also cleaned up formatting and fixed adapter outdated data bug.

2017-02-15 23:46 UTC, estebanlau approved these changes

2017-02-16 00:29 UTC, merged